spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fixturesdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
        format_sql: true

aws:
  region: ${AWS_REGION:us-east-2}
  ses:
    from: ${AWS_SES_FROM:vthangvu98@gmail.com}

rapidapi:
  key: ${RAPIDAPI_KEY}
  host: ${RAPIDAPI_HOST:free-api-live-football-data.p.rapidapi.com}